server:
  address: 127.0.0.1
  port: 9000

endpoints:
  shutdown:
    enabled: true
  jmx:
    domain: Trulogic

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enable: true
      path: /h2-ui
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  jackson:
    serialization:
      write_dates_as_timestamps: false
  http:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

api-doc:
  title: Trulogic MKombat
  description: Service for Trulogic hiring process assessment.
  version: 1.0.0
  license: LucasLBelle
  licenseUrl: https://github.com/LucasLBelle
    
